name: financial_insights
description: AI-powered personalized financial insights mobile application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1

flutter:
  uses-material-design: true
